# Site settings
title: Managing Quality
description: "A blog about the art, craft, and science of leading quality"
url: "https://jshifflet.github.io"
author:
  name: "Jason Shifflet"
  email: "jason.shifflet@gmail.com"
  url: "https://jshifflet.github.io"

# Build settings
baseurl: //
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
